/**
 * ExportButtons Component
 * 
 * Handles copying results to clipboard and downloading CSV.
 * This fulfills Feature 6: Export / Copy Results Button.
 */

import React from 'react';
import type { CalculationResults, Currency } from '../types';

interface ExportButtonsProps {
  calculations: CalculationResults;
  currency: Currency;
}

const ExportButtons: React.FC<ExportButtonsProps> = ({ calculations, currency }) => {
  const formatCurrency = (val: number) => `${currency.symbol}${val.toFixed(2)}`;

  const generateSummary = () => {
    return `Profit Margin Calculator — Results
-----------------------------------
Selling Price: ${formatCurrency(calculations.sellingPrice)}
Net Profit: ${formatCurrency(calculations.netProfit)}
Gross Margin: ${calculations.marginPercentage.toFixed(2)}%
Markup: ${calculations.markupPercentage.toFixed(2)}%
Total Costs: ${formatCurrency(calculations.totalCost)}
-----------------------------------
Generated by Profit Margin Calculator`;
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(generateSummary());
    alert('Summary copied to clipboard!');
  };

  const handleDownloadCSV = () => {
    const rows = [
      ['Metric', 'Value'],
      ['Selling Price', calculations.sellingPrice.toFixed(2)],
      ['Net Profit', calculations.netProfit.toFixed(2)],
      ['Gross Margin (%)', calculations.marginPercentage.toFixed(2)],
      ['Markup (%)', calculations.markupPercentage.toFixed(2)],
      ['Total Cost', calculations.totalCost.toFixed(2)],
      ['Currency', currency.code],
    ];

    const csvContent = "data:text/csv;charset=utf-8," + rows.map(e => e.join(",")).join("\n");
    const encodedUri = encodeURI(csvContent);
    const link = document.createElement("a");
    link.setAttribute("href", encodedUri);
    link.setAttribute("download", `profit_report_${new Date().toISOString().split('T')[0]}.csv`);
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
  };

  return (
    <div className="grid grid-cols-2 gap-4">
      <button
        onClick={handleCopy}
        className="px-4 py-2.5 bg-white/5 hover:bg-white/10 text-white text-xs font-bold rounded-xl border border-white/10 transition-all flex items-center justify-center gap-2"
      >
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M8 5H6a2 2 0 00-2 2v12a2 2 0 002 2h10a2 2 0 002-2v-1M8 5a2 2 0 002 2h2a2 2 0 002-2M8 5a2 2 0 012-2h2a2 2 0 012 2m0 0h2a2 2 0 012 2v3m2 4H10m0 0l3-3m-3 3l3 3" />
        </svg>
        Copy Summary
      </button>
      <button
        onClick={handleDownloadCSV}
        className="px-4 py-2.5 bg-white/5 hover:bg-white/10 text-white text-xs font-bold rounded-xl border border-white/10 transition-all flex items-center justify-center gap-2"
      >
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
        </svg>
        Download CSV
      </button>
    </div>
  );
};

export default ExportButtons;
